services:
  - type: web
    name: enviroai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run notebook/app.py --server.port $PORT --server.address 0.0.0.0
